# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-20 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loadfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excelfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loadfile.Folder', verbose_name='\u4e0a\u7ea7\u76ee\u5f55')),
            ],
        ),
        migrations.AddField(
            model_name='excelfile',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loadfile.Folder'),
        ),
    ]
