# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-20 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadfile', '0002_auto_20170220_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='\u751f\u6210\u65e5\u671f'),
        ),
    ]
