# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-20 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadfile', '0003_auto_20170220_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=200, verbose_name='\u6587\u4ef6\u5939\u540d'),
        ),
    ]
